AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Documentation:
  Enabled: false

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100
